package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"sync"
	"time"

	"github.com/klauspost/reedsolomon"
)

const (
	DataShards   = 8
	ParityShards  = 4
	TotalShards  = DataShards + ParityShards
)

// UploadRequest is the JSON body for the upload API.
type UploadRequest struct {
	TransferName string             `json:"transfer_name"`
	Files        []UploadFile       `json:"files"`
	ManifestHash string             `json:"manifest_hash"` // BLAKE3(K_index) hex
	ManifestData []byte             `json:"manifest_data"` // encrypted manifest
	MaxRetrievals int                `json:"max_retrievals"`
}

type UploadFile struct {
	Path     string           `json:"path"`
	Size     int64            `json:"size"`
	Segments []UploadSegment  `json:"segments"`
}

type UploadSegment struct {
	ID             string `json:"id"`
	EncryptedSize  int    `json:"encrypted_size"`
	EncryptedData  []byte `json:"encrypted_data"` // encrypted by browser
}

// UploadResponse is returned after successful upload.
type UploadResponse struct {
	Code       string `json:"code"`
	TransferName string `json:"transfer_name"`
	Files      int    `json:"files"`
	TotalBytes int64  `json:"total_bytes"`
}

func (s *Server) uploadHandler(w http.ResponseWriter, req *http.Request) {
	if req.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	// Parse the multipart/JSON body
	var upload UploadRequest
	if err := json.NewDecoder(req.Body).Decode(&upload); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if len(upload.Files) == 0 {
		writeError(w, http.StatusBadRequest, "no files")
		return
	}

	if upload.MaxRetrievals <= 0 {
		upload.MaxRetrievals = 1
	}

	// Erasure code each segment and upload shards
	enc, err := reedsolomon.New(DataShards, ParityShards)
	if err != nil {
		log.Printf("Reed-Solomon init error: %v", err)
		writeError(w, http.StatusInternalServerError, "erasure coding error")
		return
	}

	manifest := buildManifestJSON(upload)
	var totalBytes int64

	for fileIdx, f := range upload.Files {
		totalBytes += f.Size
		for segIdx, seg := range f.Segments {
			// Split encrypted data into shards
			shards, err := enc.Split(seg.EncryptedData)
			if err != nil {
				log.Printf("Split error: %v", err)
				writeError(w, http.StatusInternalServerError, "erasure split error")
				return
			}

			if err := enc.Encode(shards); err != nil {
				log.Printf("Encode error: %v", err)
				writeError(w, http.StatusInternalServerError, "erasure encode error")
				return
			}

			// Upload each shard to storage nodes
			shardInfos := []map[string]interface{}{}
			for shardIdx, shard := range shards {
				if shard == nil {
					continue
				}
				hash := sha256Sum(shard)
				node := s.storageNodes[shardIdx%len(s.storageNodes)]

				if err := uploadShard(node, hash, shard); err != nil {
					log.Printf("Shard upload error: %v", err)
					writeError(w, http.StatusInternalServerError, "shard upload failed")
					return
				}

				shardInfos = append(shardInfos, map[string]interface{}{
					"index": shardIdx,
					"hash":  hash,
					"node":  node,
				})
			}

			manifest["files"].([]map[string]interface{})[fileIdx]["segments"].([]map[string]interface{})[segIdx]["shards"] = shardInfos
		}
	}

	// Encrypt manifest is already done by browser — upload.ManifestData is the encrypted manifest
	// Upload manifest to relay with max retrievals
	if err := uploadManifest(s.relayURL, upload.ManifestHash, upload.ManifestData, upload.MaxRetrievals); err != nil {
		log.Printf("Manifest upload error: %v", err)
		writeError(w, http.StatusInternalServerError, "manifest upload failed")
		return
	}

	// Save transfer record
	senderEmail, _ := s.getUserEmail(req)
	record := &TransferRecord{
		Code:         "", // code is generated by browser, not stored here for security
		SenderEmail:  senderEmail,
		TransferName: upload.TransferName,
		Files:        len(upload.Files),
		TotalBytes:   totalBytes,
		CreatedAt:    time.Now(),
	}
	if record.Code == "" {
		record.Code = "web-upload"
	}
	s.db.SaveTransfer(record)

	writeJSON(w, http.StatusOK, UploadResponse{
		TransferName: upload.TransferName,
		Files:        len(upload.Files),
		TotalBytes:   totalBytes,
	})
}

func buildManifestJSON(upload UploadRequest) map[string]interface{} {
	files := []map[string]interface{}{}
	for _, f := range upload.Files {
		segs := []map[string]interface{}{}
		for _, seg := range f.Segments {
			segs = append(segs, map[string]interface{}{
				"id":             seg.ID,
				"original_size":  0,
				"encrypted_size": seg.EncryptedSize,
				"shards":         []map[string]interface{}{},
			})
		}
		files = append(files, map[string]interface{}{
			"path":     f.Path,
			"size":     f.Size,
			"segments": segs,
		})
	}
	return map[string]interface{}{
		"version":               1,
		"transfer_name":         upload.TransferName,
		"total_bytes":           0,
		"segment_size":          67108864,
		"erasure_data_shards":   DataShards,
		"erasure_parity_shards": ParityShards,
		"files":                 files,
	}
}

func sha256Sum(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}

func uploadShard(nodeURL, hash string, data []byte) error {
	url := nodeURL + "/shard/" + hash
	req, err := http.NewRequest(http.MethodPut, url, bytes.NewReader(data))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/octet-stream")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return fmt.Errorf("shard upload to %s returned %d", nodeURL, resp.StatusCode)
	}
	return nil
}

func uploadManifest(relayURL, hash string, data []byte, maxRetrievals int) error {
	url := relayURL + "/manifest/" + hash
	req, err := http.NewRequest(http.MethodPut, url, bytes.NewReader(data))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/octet-stream")
	req.Header.Set("X-Max-Retrievals", intToStr(maxRetrievals))
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return fmt.Errorf("manifest upload returned %d", resp.StatusCode)
	}
	return nil
}

func intToStr(n int) string {
	return fmt.Sprintf("%d", n)
}

// Concurrent shard upload helper
func uploadShardsConcurrently(nodeURL string, shards map[string][]byte) error {
	var wg sync.WaitGroup
	errCh := make(chan error, len(shards))

	for hash, data := range shards {
		wg.Add(1)
		go func(h string, d []byte) {
			defer wg.Done()
			if err := uploadShard(nodeURL, h, d); err != nil {
				errCh <- err
			}
		}(hash, data)
	}

	wg.Wait()
	close(errCh)
	for err := range errCh {
		if err != nil {
			return err
		}
	}
	return nil
}

var _ = io.Copy
var _ = log.Printf
